#!/usr/bin/env bash
# installs and configures HAProxy on lb-01 server
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e 'frontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n' | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e 'backend backendnodes\n\tbalance roundrobin\n\tserver node1 35.243.251.251:80 check\n\tserver node2 34.73.23.24:80 check\n' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
