#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=':' read -r user password uid gid userinfo home_dir cmd; do
	echo "The user $user is part of the $gid gang, lives in $home_dir and rides $cmd. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < "/etc/passwd"
