#!/usr/bin/env bash
# checks if the file exists and print:
#
# if the file exists: holbertonschool file exists
# if the file does not exist: holbertonschool file does not exist
#
# if the file exists, print:
#
# if the file is empty: holbertonschool file is empty
# if the file is no empty: holbertonschool file is not empty
# if the file is a regular file: holbertonschool is a regular file
# if the file is not a regular file: (nothing)
file="holbertonschool"
if [ -e "$file" ]; then
	echo "$file file exists"
	if [ -s "$file" ]; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	if [ -f "$file" ]; then
		echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi
