#!/usr/bin/env bash
# configures a new Ubuntu machine to respect requirements
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx restart
