#!/usr/bin/env bash
# configure the nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
replacer="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "/listen 80 default_server/ a \\t$replacer" /etc/nginx/sites-available/default
sudo service nginx restart
