#!/usr/bin/env bash
# configure the nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "/listen 80 default_server/ a \\tlocation /redirect_me {\n\t\treturn 301 https://http.cat/;\n}\n" /etc/nginx/sites-available/default
sudo service nginx restart
