#!/usr/bin/env bash
# configure the nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx restart
sudo touch /usr/share/nginx/html/404.html
sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo service nginx restart
