#!/usr/bin/env bash
# runs Nginx as nginx user rather than su
pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
